name: 'images'
description: 'Build container images'
inputs:
  build-opts: 
    description: 'build options in YAML format (see README.md)'
    required: true
  registry: 
    description: 'registry'
    required: true
  tag:
    description: 'image tag'
    required: true
  platforms:
    description: 'platforms'
    required: false
    default: ''
  operation:
    description: '<push|build|build-and-push>'
    required: true
  latest:
    description: 'latest tag'
    required: false
    default: 'false'
  cache-from:
    description: 'cache from https://docs.docker.com/build/ci/github-actions/cache/'
    required: false
    default: ''
  cache-to:
    description: 'cache from https://docs.docker.com/build/ci/github-actions/cache/'
    required: false
    default: ''
  github-token: 
    description: 'github token'
    required: false
    default: ''
  repo-name:
    description: 'override repo name'
    required: false
    default: ''
  image-naming-strategy: 
    description: 'image naming strategy <multi-repo|single-repo>'
    required: false
    default: 'multi-repo'
  ci:
    description: 'only build with tmp tag'
    required: false
    default: 'false'
  ci-tag:
    description: 'tmp tag for ci build'
    required: false
    default: '{{ commit }}'
    
outputs:
  copy-files:
    description: 'copy files'
  build-opts:
    description: 'build opts'
  pushed-images:
    description: 'pushed images'
  built-images:
    description: 'built images'

runs:
  using: 'node24'
  main: 'dist/main.js'