name: 'images'
description: 'Build container images'
inputs:
  build-opts: 
    description: 'build options in YAML format (see README.md)'
    required: true
  registry: 
    description: 'registry'
    required: true
  tag:
    description: 'image tag'
    required: true
  platforms:
    description: 'platforms'
    required: false
    default: ''
  operation:
    description: '<push|build|build-and-push>'
    required: true
  latest:
    description: 'latest tag'
    required: false
    default: 'false'
  cache-from:
    description: 'cache from https://docs.docker.com/build/ci/github-actions/cache/'
    required: false
    default: ''
  cache-to:
    description: 'cache from https://docs.docker.com/build/ci/github-actions/cache/'
    required: false
    default: ''
  github-token: 
    description: 'github token'
    required: false
    default: ''

outputs:
  copy-files:
    description: 'copy files'
  build-opts:
    description: 'build opts'
  pushed-images:
    description: 'pushed images'
  built-images:
    description: 'built images'

runs:
  using: 'node20'
  main: 'dist/main.js'